package com.javacoders.websocketizer.autogenerated;

import java.io.IOException;
import java.lang.String;
import java.lang.System;
import javax.websocket.CloseReason;
import javax.websocket.OnClose;
import javax.websocket.OnMessage;
import javax.websocket.OnOpen;
import javax.websocket.Session;
import javax.websocket.server.ServerEndpoint;

@ServerEndpoint("/hello")
public class HelloWorld {
  @OnOpen
  public void onOpen(Session session) {
    System.out.println("WebSocket Opened!");
  }

  @OnMessage
  public void onMessage(String message, Session session) throws IOException {
    session.getBasicRemote().sendText("Hello!");
  }

  @OnClose
  public void onClose(CloseReason reason, Session session) {
    System.out.println("WebSocket Closed!");
  }
}
