package com.javacoders.service.rs.autogenerated;

import java.io.IOException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.String;
import java.lang.System;
import java.util.List;
import javax.websocket.CloseReason;
import javax.websocket.OnClose;
import javax.websocket.OnMessage;
import javax.websocket.OnOpen;
import javax.websocket.Session;
import javax.websocket.server.ServerEndpoint;

@ServerEndpoint("/hello/GET")
public class RestService_hello_GET {
  @OnOpen
  public void onOpen(Session session) throws IOException {
    System.out.println("WebSocket Opened!");
  }

  @OnMessage
  public void onMessage(String message, Session session) throws IOException, InstantiationException, IllegalAccessException {
    List<Object> params = com.javacoders.service.rs.autogenerated.Util.parseMessage(message, Void.class);
    com.javacoders.service.rs.RestService service = com.javacoders.service.rs.RestService.class.newInstance();
    session.getBasicRemote().sendText(com.javacoders.service.rs.autogenerated.Util.getJson(service.hello()));
  }

  @OnClose
  public void onClose(CloseReason reason, Session session) throws IOException {
    session.close();
    System.out.println("WebSocket Closed!");
  }
}
