package com.javacoders.websocketizer.cogen;

import java.io.File;
import java.io.IOException;

import com.javacoders.websocketizer.ServiceBlueprint;
import com.javacoders.websocketizer.rest.RestServiceBlueprint;

/**
 * Code Generator (a.k.a. CoGen) is responsible for taking any generic web
 * service represented by a {@link RestServiceBlueprint} and automatically
 * generating a Web Socket service which exposes the same functionality as the
 * service represented by this {@link RestServiceBlueprint}. The service
 * blueprint is generated by Pattern Identifier (a.k.a. PI).
 * 
 * @author shivam.maharshi
 */
public interface CodeGenerator {

  /**
   * Takes a {@link RestServiceBlueprint} created by PI after parsing the web
   * service to be automatically converted into Web Socket service.
   * 
   * @param sb
   * @throws IOException
   */
  public void generate(ServiceBlueprint sb, File dir);

}
