package com.javacoders.websocketizer;

import java.util.List;

/**
 * An interface that defines the essential functionality of an object
 * representing a service.
 * 
 * @author shivam.maharshi
 */
public interface ServiceBlueprint {
  
  public String getEndpoint();
  
  public String getClassName();
  
  public String getPackageName();
  
  public String getSourceDir();
  
  public String getAutogeneratedPath();
  
  public Framework getFramework();
  
  public List<InputParam> getInputs();
  
  public RequestHandler getRequestHandler();
  
  public RequestContext getRequestContext();

}
